name: past
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - sympy
  - openpyxl
  - jupyterlab
  - scipy
  - seaborn
  - scikit-learn
  - open3d  
  - pip
  - pip:
      - torch
      - pathlib
